package dashboard

import (
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"testing"
)

func TestTemplRuntimePolicyIsDeterministic(t *testing.T) {
	policy := templRuntimePolicy()

	if policy.Mode != "checked-in-generated" {
		t.Fatalf("expected deterministic templ mode checked-in-generated, got %q", policy.Mode)
	}
	if policy.RuntimeGenerationAllowed {
		t.Fatal("expected runtime generation to be disabled")
	}
	if policy.GenerateCommand == "" {
		t.Fatal("expected explicit templ generate command policy")
	}
}

// TestStaticAssetByteFloors asserts that the embedded StaticFS contains real
// (non-stub) static assets. Satisfies REQ-100.
func TestStaticAssetByteFloors(t *testing.T) {
	tests := []struct {
		name     string
		path     string
		minBytes int64
	}{
		{
			name:     "htmx.min.js",
			path:     "static/htmx.min.js",
			minBytes: 40_000,
		},
		{
			name:     "pico.min.css",
			path:     "static/pico.min.css",
			minBytes: 60_000,
		},
		{
			name:     "styles.css",
			path:     "static/styles.css",
			minBytes: 20_000,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			info, err := fs.Stat(StaticFS, tt.path)
			if err != nil {
				t.Fatalf("fs.Stat(%q) failed: %v\nPossible cause: static asset not embedded or path is wrong.", tt.path, err)
			}
			if info.Size() < tt.minBytes {
				t.Fatalf(
					"%s size = %d bytes; expected >= %d bytes.\nPossible cause: the file is still a stub. Copy the real asset from engram-cloud/internal/cloud/dashboard/static/.",
					tt.path, info.Size(), tt.minBytes,
				)
			}
		})
	}
}

// TestTemplGeneratedFilesAreCheckedIn asserts that the templ-generated *_templ.go
// files are committed alongside the .templ sources. Satisfies REQ-101.
func TestTemplGeneratedFilesAreCheckedIn(t *testing.T) {
	_, callerFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	pkgDir := filepath.Dir(callerFile)

	headerRe := regexp.MustCompile(`(?m)^// Code generated by templ`)

	tests := []struct {
		name     string
		file     string
		minBytes int64
	}{
		{
			name:     "components_templ.go",
			file:     "components_templ.go",
			minBytes: 100_000,
		},
		{
			name:     "layout_templ.go",
			file:     "layout_templ.go",
			minBytes: 1,
		},
		{
			name:     "login_templ.go",
			file:     "login_templ.go",
			minBytes: 1,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			fullPath := filepath.Join(pkgDir, tt.file)
			info, err := os.Stat(fullPath)
			if err != nil {
				t.Fatalf(
					"%s not found at %s: %v\nPossible cause: the *.templ sources changed but the generated *_templ.go files were not committed. Run `make templ` and commit the regenerated files.",
					tt.file, fullPath, err,
				)
			}
			if info.Size() < tt.minBytes {
				t.Fatalf(
					"%s size = %d bytes; expected >= %d bytes.\nPossible cause: the *.templ sources changed but the generated *_templ.go files were not committed. Run `make templ` (or `go tool templ generate ./internal/cloud/dashboard/...`) and commit the regenerated files.",
					tt.file, info.Size(), tt.minBytes,
				)
			}
			content, err := os.ReadFile(fullPath)
			if err != nil {
				t.Fatalf("os.ReadFile(%s) failed: %v", fullPath, err)
			}
			preview := content
			if len(preview) > 1024 {
				preview = preview[:1024]
			}
			if !headerRe.Match(preview) {
				t.Fatalf(
					"%s does not start with '// Code generated by templ' header.\nFirst 1024 bytes: %q\nPossible cause: the file is hand-written, not generated. Run `make templ` and commit.",
					tt.file, string(preview),
				)
			}
		})
	}
}

// canonicalTemplGenerateCommand is the single codegen invocation Engram
// documents, advertises through TemplRuntimePolicy, and wires into
// //go:generate directives. It resolves templ through the module's tool
// directive so contributors never need templ on PATH.
const canonicalTemplGenerateCommand = "go tool templ generate"

// repoRootFile reads a file from the repository root, located relative to this
// test's own source path (internal/cloud/dashboard -> three levels up).
func repoRootFile(t *testing.T, name string) string {
	t.Helper()

	_, callerFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	root := filepath.Join(filepath.Dir(callerFile), "..", "..", "..")

	content, err := os.ReadFile(filepath.Join(root, name))
	if err != nil {
		t.Fatalf("read %s from repo root: %v", name, err)
	}
	return string(content)
}

// TestTemplGenerateCommandIsExecutable asserts that the codegen command Engram
// advertises is actually runnable. `go tool templ generate` only resolves when
// go.mod declares the matching tool directive; without it the command fails
// with `go: no such tool "templ"`, which is what contributors hit when they
// follow DOCS.md.
func TestTemplGenerateCommandIsExecutable(t *testing.T) {
	if got := templRuntimePolicy().GenerateCommand; got != canonicalTemplGenerateCommand {
		t.Fatalf(
			"TemplRuntimePolicy.GenerateCommand = %q, want %q.\nPossible cause: the advertised codegen command drifted from the one the docs and //go:generate directives use.",
			got, canonicalTemplGenerateCommand,
		)
	}

	const toolDirective = "tool github.com/a-h/templ/cmd/templ"
	if !strings.Contains(repoRootFile(t, "go.mod"), toolDirective) {
		t.Fatalf(
			"go.mod does not declare %q.\nPossible cause: the tool directive was removed, which breaks %q with `go: no such tool \"templ\"`. Restore it with `go get -tool github.com/a-h/templ/cmd/templ`.",
			toolDirective, canonicalTemplGenerateCommand,
		)
	}
}

// TestTemplGenerateDirectivesAreCanonical asserts that every //go:generate
// directive that drives templ in this package uses the canonical command, so
// `go generate ./...` never falls back to a bare `templ` binary on PATH.
func TestTemplGenerateDirectivesAreCanonical(t *testing.T) {
	_, callerFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	pkgDir := filepath.Dir(callerFile)

	entries, err := os.ReadDir(pkgDir)
	if err != nil {
		t.Fatalf("os.ReadDir(%s) failed: %v", pkgDir, err)
	}

	directiveRe := regexp.MustCompile(`(?m)^//go:generate .*templ generate.*$`)

	found := 0
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		content, err := os.ReadFile(filepath.Join(pkgDir, entry.Name()))
		if err != nil {
			t.Fatalf("os.ReadFile(%s) failed: %v", entry.Name(), err)
		}
		for _, directive := range directiveRe.FindAllString(string(content), -1) {
			found++
			want := "//go:generate " + canonicalTemplGenerateCommand
			if strings.TrimSpace(directive) != want {
				t.Errorf(
					"%s declares %q, want %q.\nPossible cause: a bare `templ generate` directive requires templ on PATH and fails for contributors who only ran `go mod download`.",
					entry.Name(), strings.TrimSpace(directive), want,
				)
			}
		}
	}

	if found == 0 {
		t.Fatal("no //go:generate templ directive found in the dashboard package; expected at least one")
	}
}
